version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_db
    environment:
      MYSQL_DATABASE: rental_mysqldb
      MYSQL_USER: user_sva
      MYSQL_PASSWORD: 041002
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d

  web:
    build:
      dockerfile: Dockerfile
    container_name: myproject
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=rental_mysqldb
      - DB_USER=user_sva
      - DB_PASSWORD=041002

volumes:
  db_data:
