# Generated by Django 5.2.6 on 2025-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Количество просмотров объявления"
            ),
        ),
    ]
