# Generated by Django 5.2.6 on 2025-10-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_booking_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
            },
        ),
    ]
